package com.github.fridayai.fridayintellijextension.constants

class MessageTypes {
    companion object {
        val IDE_MESSAGE_TYPES = listOf(
            "readRangeInFile",
            "getUniqueId",
            "getDiff",
            "getTerminalContents",
            "getWorkspaceDirs",
            "showLines",
            "writeFile",
            "fileExists",
            "removeFile",
            "showVirtualFile",
            "openFile",
            "runCommand",
            "saveFile",
            "readFile",
            "showDiff",
            "getOpenFiles",
            "getCurrentFile",
            "getPinnedFiles",
            "getSearchResults",
            "getFileResults",
            "getProblems",
            "subprocess",
            "getBranch",
            "getTags",
            "getIdeInfo",
            "getIdeSettings",
            "getRepoName",
            "listDir",
            "getGitRootPath",
            "getFileStats",
            "insertAtCursor",
            "applyToFile",
            "showToast",
            "openUrl",
            "isWorkspaceRemote",

            // These only come from the GUI for now but should be here to prevent confusion
            "toggleDevTools",
            "showTutorial",

            // These are jetbrains only and only come from the GUI for now
            // But again including for consistency
            "copyText",
            "jetbrains/isOSREnabled",
            "jetbrains/getColors",
            "jetbrains/onLoad"
        )

        // Note: If updating these values, make a corresponding update in
        // core/protocol/passThrough.ts
        val PASS_THROUGH_TO_WEBVIEW = listOf(
            "configUpdate",
            "indexProgress", // Codebase
            "indexing/statusUpdate", // Docs, etc.
            "addContextItem",
            "refreshSubmenuItems",
            "isFridayInputFocused",
            "setTTSActive",
            "getWebviewHistoryLength",
            "getCurrentSessionId",
            "sessionUpdate",
            "didCloseFiles",
            "toolCallPartialOutput",
            "navigateTo",
            "focusContinueInput",
            "focusContinueInputWithoutClear",
        )

        // Note: If updating these values, make a corresponding update in
        // core/protocol/passThrough.ts
        val PASS_THROUGH_TO_CORE = listOf(
            "abort",
            "history/list",
            "history/delete",
            "history/load",
            "history/save",
            "history/loadRemote",
            "history/clear",
            "history/clearWorkspace",
            "devdata/log",
            "config/addModel",
            "config/newPromptFile",
            "config/newAssistantFile",
            "config/ideSettingsUpdate",
            "settings/get",
            "settings/save",
            "config/addLocalWorkspaceBlock",
            "config/addGlobalRule",
            "config/debug",
            "config/deleteRule",
            "config/getSerializedProfileInfo",
            "config/deleteModel",
            "config/deleteProfile",
            "config/renameProfile",
            "config/renamePrompt",
            "config/renameRule",
            "config/deletePrompt",
            "config/addGlobalBlock",
            "config/refreshProfiles",
            "config/openProfile",
            "config/updateSharedConfig",
            "config/updateSelectedModel",
            "mcp/reloadServer",
            "mcp/startAuthentication",
            "mcp/removeAuthentication",
            "mcp/setServerEnabled",
            "mcp/getPrompt",
            "context/getContextItems",
            "context/getSymbolsForFiles",
            "context/loadSubmenuItems",
            "context/addDocs",
            "context/removeDocs",
            "context/indexDocs",
            "autocomplete/complete",
            "autocomplete/cancel",
            "autocomplete/accept",
            "nextEdit/predict",
            "nextEdit/reject",
            "nextEdit/accept",
            "nextEdit/startChain",
            "nextEdit/deleteChain",
            "nextEdit/isChainAlive",
            "nextEdit/queue/getProcessedCount",
            "nextEdit/queue/dequeueProcessed",
            "nextEdit/queue/processOne",
            "nextEdit/queue/clear",
            "nextEdit/queue/abort",
            "tts/kill",
            "llm/complete",
            "llm/streamChat",
            "llm/listModels",
            "llm/compileChat",
            "streamDiffLines",
            "getDiffLines",
            "chatDescriber/describe",
            "conversation/compact",
            "stats/getTokensPerDay",
            "stats/getTokensPerModel",
            // Codebase
            "index/setPaused",
            "index/forceReIndex",
            "index/forceReIndexFiles",
            "index/indexingProgressBarInitialized",
            // Docs, etc.
            "indexing/reindex",
            "indexing/abort",
            "indexing/setPaused",
            "docs/initStatuses",
            "docs/getDetails",
            "docs/getIndexedPages",
            //
            "onboarding/complete",
            "addAutocompleteModel",
            "didChangeSelectedProfile",
            "didChangeSelectedOrg",
            "tools/call",
            "tools/evaluatePolicy",
            "tools/preprocessArgs",
            "controlPlane/getEnvironment",
            "controlPlane/getCreditStatus",
            "controlPlane/openUrl",
            "isItemTooBig",
            "process/markAsBackgrounded",
            "process/isBackgrounded",
            "process/killTerminalProcess",
            "models/fetch"
        )
    }
}
